services:
  data-downloader-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASS
      POSTGRES_AUDIT_PASS: $POSTGRES_AUDIT_PASS
      POSTGRES_USER_PASS: $POSTGRES_USER_PASS
      PGDATA: /var/lib/postgresql/data/pgdata
    build:
      context: ../..
      dockerfile: docker/Postgres.Dockerfile     
    ports:
      - "5430:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - dd-net

  data-downloader-webapi:
    container_name: webapi
    build:
      context: ../..
      dockerfile: docker/Web.Api.Dockerfile
    environment:
      ConnectionStrings__UserDBConnection: $WEBAPI_USER_DB_CONNECTION
      RabbitMQConnections__0__Host: $RABBIT_CONNECTION_HOST
      RabbitMQConnections__0__Port: $RABBIT_CONNECTION_PORT
      RabbitMQConnections__0__VirtualHost: $RABBIT_CONNECTION_VIRTUAL_HOST
      RabbitMQConnections__0__UserName: $RABBIT_CONNECTION_WEBAPI_USERNAME
      RabbitMQConnections__0__Password: $RABBIT_CONNECTION_WBAPI_PASSWORD
      RabbitMQConnections__0__ExchangeName: $RABBIT_CONNECTION_EXCHANGE_FILE_TO_PROCESSING
    depends_on:
      data-downloader-postgres:
        condition: service_healthy
    ports:
      - "5100:8080"
    restart: always
    networks:
      - dd-net     
      
  data-downloader-rabbit:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_PASS=$RABBIT_PASS
    build:
        context: ../..
        dockerfile: docker/Rabbit.Dockerfile
    volumes:
        - rabbit_data:/var/lib/rabbitmq/
    ports:
        - 15672:15672
        - 5672:5672
    healthcheck:
        test: rabbitmq-diagnostics -q status
        interval: 45s
        timeout: 45s
        retries: 8
    restart: always   
    networks:
      - dd-net  
      
volumes:
  pg_data: null
  rabbit_data: null  
  
networks:
  dd-net: