set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE dd_audit WITH LOGIN PASSWORD '$POSTGRES_AUDIT_PASS';
	CREATE DATABASE dd_audit WITH OWNER = dd_audit;
	GRANT ALL PRIVILEGES ON DATABASE dd_audit TO dd_audit;

	CREATE ROLE dd_user WITH LOGIN PASSWORD '$POSTGRES_USER_PASS';
	CREATE DATABASE dd_user WITH OWNER = dd_user;
	GRANT ALL PRIVILEGES ON DATABASE dd_user TO dd_user;
EOSQL
